### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by TigerCubDen** [JamzumSum/Qzone2TG#25]
```
[INFO] 2021 Sep 21 10:21:24 Main: config loaded
[INFO] 2021 Sep 21 10:21:25 apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
[INFO] 2021 Sep 21 10:21:25 apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
[INFO] 2021 Sep 21 10:21:26 apscheduler.scheduler: Added job "cleanFeed" to job store "default"
[INFO] 2021 Sep 21 10:21:26 apscheduler.scheduler: Added job "cleanFeed" to job store "default"
[INFO] 2021 Sep 21 10:21:26 apscheduler.scheduler: Scheduler started
[WARNING] 2021 Sep 21 10:21:26 apscheduler.executors.default: Run time of job "cleanFeed (trigger: date[2021-09-21 10:21:25 UTC], next run at: 2021-09-21 10:21:25 UTC)" was missed by 0:00:01.314897
[INFO] 2021 Sep 21 10:21:26 apscheduler.scheduler: Removed job ea91d4bfbec04d458129752f8c1dfd57
[INFO] 2021 Sep 21 10:21:27 frontend.tg: start polling
Traceback (most recent call last):
  File "/app/src/__main__.py", line 186, in <module>
Login as: 1407420178
    main([i for i in sys.argv[1:] if not i.startswith('-')])
  File "/app/src/__main__.py", line 157, in main
    bot.run()
  File "/app/src/frontend/tg/__init__.py", line 251, in run
    self.idle()
  File "/app/src/frontend/tg/__init__.py", line 266, in idle
    self.register_period_refresh()
  File "/app/src/frontend/tg/__init__.py", line 64, in register_period_refresh
    days=tuple(self.daily.get('days', range(7)))
AttributeError: 'str' object has no attribute 'get'
```

**Comment by JamzumSum** [comment]
似乎是因为`daily`传了字符串? `daily`是一个字典, 详见https://github.com/JamzumSum/Qzone2TG/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E6%A1%A3#%E5%AE%9A%E6%97%B6

另, 请注意保护您的个人信息:D

**Comment by JamzumSum** [comment]
![image](https://user-images.githubusercontent.com/22952836/134179338-5e66a40e-f039-45c6-875e-9e8f899af03e.png)
~~~ yaml
log:
  level: info
  format: '[%(levelname)s] %(asctime)s %(name)s: | %(message)s '
bot:
  accept_id: ${oc.env:TEST_ACCEPTID}
  method: polling
  proxy:
    proxy_url: socks5://127.0.0.1:7890
  token: ${oc:.env:TEST_BOT_TOKEN}
  daily:
    time: ["08:00", "09:00", "09:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", 
    "19:00", "20:00", "21:00", "22:00", "23:00"]
feed:
  keepdays: 3
qzone:
  UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62
  qq: ${oc.env:TEST_UIN}
  qr_strategy: allow
~~~
以上是复现配置和开始运行之后的日志, 看起来并没有遇到这个问题)
不知道您是否同步了最新的commit?

**Comment by TigerCubDen** [comment]
> ![image](https://user-images.githubusercontent.com/22952836/134179338-5e66a40e-f039-45c6-875e-9e8f899af03e.png)
> 
> ```yaml
> log:
>   level: info
>   format: '[%(levelname)s] %(asctime)s %(name)s: | %(message)s '
> bot:
>   accept_id: ${oc.env:TEST_ACCEPTID}
>   method: polling
>   proxy:
>     proxy_url: socks5://127.0.0.1:7890
>   token: ${oc.env:TEST_BOT_TOKEN}
>   daily:
>     time: ["08:00", "09:00", "09:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", 
>     "19:00", "20:00", "21:00", "22:00", "23:00"]
> feed:
>   keepdays: 3
> qzone:
>   UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
>     Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62
>   qq: ${oc.env:TEST_UIN}
>   qr_strategy: allow
> ```
> 
> 以上是复现配置和开始运行之后的日志, 看起来并没有遇到这个问题)
> 不知道您是否同步了最新的commit?

同步最新 commit 的 docker 镜像和您提供的 docker 镜像都试了一遍，是同样的问题。

**Comment by JamzumSum** [comment]
> 同步最新 commit 的 docker 镜像和您提供的 docker 镜像都试了一遍，是同样的问题。

我把`auto_start`设为`True`也没有重现此问题;
检查所有`daily`为左值的情况也并没有发现奇怪的赋值;
看起来您的`daily`配置似乎也没什么问题

这样的话 可能需要您帮助调试一下——看看`self.daily`的值是什么 以便于猜出来到底是哪里出了问题(x

**Comment by TigerCubDen** [comment]
我把整个配置文件删了重建就好了 XD

**Comment by TigerCubDen** [comment]
谢谢开发者~ 这个 issue 可以删掉了。
