### ISSUE TITLE
Qzone return HTTP 502

### ISSUE THREAD

**Issue by JamzumSum** [JamzumSum/Qzone2TG#38]
~~~
[DEBUG] 2021 Oct 20 18:04:49 urllib3.connectionpool: | https://user.qzone.qq.com:443 "GET /proxy/domain/ic2.qzone.qq.com/cgi-bin/feeds/cgi_get_feeds_count.cgi?uin=***&rd=0.01858311715012806&g_tk=*** HTTP/1.1" 502 161
[ERROR] 2021 Oct 20 18:04:49 frontend.tg.base: | Uncaught error when fetch                                                      
Traceback (most recent call last):
  File "/root/Qzone2TG/src/frontend/tg/base.py", line 141, in onFetch                                                           
    r = self.feedmgr.fetchNewFeeds(no_pred=not period, ignore_exist=reload)                                                     
  File "/root/Qzone2TG/src/qzone/feed.py", line 188, in fetchNewFeeds                                                           
    f"{type(e)} when fetching pages: " + str(e),
UnboundLocalError: local variable 'e' referenced before assignment
~~~

Just ignore the UnboundLocalError which will soon be fixed...
Of course Qzone has no trouble with their server. So the reason for 502 is puzzling.

This happens after but not right after relogin. A few heartbeats did succeed after that.
Qzone may return these codes to refuse our requests....?

**Comment by JamzumSum** [comment]
Seems 502 code is not relevant with relogin. Title is changed.

**Comment by JamzumSum** [comment]
Since this hasn't occured for a period of time, this issue will be closed.
Maybe it would be nice to add this to FAQ as a record.
